// src\lib\mockCars.ts
import type { Car } from '@/types';

const now = Date.now();
const DAY = 24 * 60 * 60 * 1000;

// ============================================
// 日本語名 → slug 変換辞書
// ============================================

const MAKER_TO_SLUG: Record<string, string> = {
  'トヨタ': 'toyota',
  'ホンダ': 'honda',
  '日産': 'nissan',
  'スズキ': 'suzuki',
  'マツダ': 'mazda',
  'スバル': 'subaru',
  'ダイハツ': 'daihatsu',
  '三菱': 'mitsubishi',
  'レクサス': 'lexus',
  'メルセデス・ベンツ': 'mercedes-benz',
  'BMW': 'bmw',
  'フォルクスワーゲン': 'volkswagen',
  'アウディ': 'audi',
  'ボルボ': 'volvo',
  'MINI': 'mini',
  'ジープ': 'jeep',
  'プジョー': 'peugeot',
};

const PREF_TO_SLUG: Record<string, string> = {
  '東京都': 'tokyo',
  '神奈川県': 'kanagawa',
  '千葉県': 'chiba',
  '埼玉県': 'saitama',
  '大阪府': 'osaka',
  '兵庫県': 'hyogo',
  '京都府': 'kyoto',
  '愛知県': 'aichi',
  '静岡県': 'shizuoka',
  '福岡県': 'fukuoka',
  '熊本県': 'kumamoto',
  '宮城県': 'miyagi',
};

const CITY_TO_SLUG: Record<string, string> = {
  '横浜市': 'yokohama',
  '川崎市': 'kawasaki',
  '名古屋市': 'nagoya',
  '大阪市': 'osaka',
  '京都市': 'kyoto',
  '神戸市': 'kobe',
  '福岡市': 'fukuoka',
  '仙台市': 'sendai',
  '千葉市': 'chiba',
  'さいたま市': 'saitama',
  '浜松市': 'hamamatsu',
  '熊本市': 'kumamoto',
  '堺市': 'sakai',
  '豊田市': 'toyota',
  '船橋市': 'funabashi',
  '港区': 'minato',
  '渋谷区': 'shibuya',
  '世田谷区': 'setagaya',
  '新宿区': 'shinjuku',
};

/**
 * モデル名からslugを生成（簡易版）
 * 本番ではDB側でslugを管理する想定
 */
function modelToSlug(model: string): string {
  // 仕様: modelSlug は「車種シリーズ」粒度に統一する（グレードは含めない）
  // 例: "プリウス S" → "prius"

  const baseName = model.trim().split(/\s+/)[0] || model.trim();

  const seriesMap: Record<string, string> = {
    'プリウス': 'prius',
    'アクア': 'aqua',
    'ハリアー': 'harrier',
    'アルファード': 'alphard',
    'ヤリス': 'yaris',
    'RAV4': 'rav4',
    'カローラツーリング': 'corolla-touring',
    'N-BOX': 'n-box',
    'フィット': 'fit',
    'ヴェゼル': 'vezel',
    'フリード': 'freed',
    'ステップワゴン': 'stepwagon',
    'シビック': 'civic',
    'ノート': 'note',
    'セレナ': 'serena',
    'エクストレイル': 'x-trail',
    'リーフ': 'leaf',
    'キックス': 'kicks',
    'ジムニー': 'jimny',
    'スペーシア': 'spacia',
    'ハスラー': 'hustler',
    'ワゴンR': 'wagonr',
    'アルト': 'alto',
    'CX-5': 'cx-5',
    'CX-8': 'cx-8',
    'MAZDA3': 'mazda3',
    'CX-30': 'cx-30',
    'ロードスター': 'roadster',
    'タント': 'tanto',
    'ムーヴ': 'move',
    'ロッキー': 'rocky',
    'フォレスター': 'forester',
    'インプレッサ': 'impreza',
    'XV': 'xv',
    'レヴォーグ': 'levorg',
    'デリカ': 'delica',
    'eKワゴン': 'ek-wagon',
    'アウトランダーPHEV': 'outlander-phev',
    'NX300h': 'nx300h',
    'RX450h': 'rx450h',
    'CT200h': 'ct200h',
    'Cクラス': 'c-class',
    '3シリーズ': '3-series',
    'ゴルフ': 'golf',
    'A4': 'a4',
    'XC60': 'xc60',
    'MINI': 'mini',
    'ラングラー': 'wrangler',
    '308': '308',
  };

  return seriesMap[baseName] || baseName.toLowerCase().replace(/\s+/g, '-');
}

function inferFeatureSlugs(modelSeriesSlug: string): string[] {
  // 最小の動作確認用。必要に応じて増やす。
  const map: Record<string, string[]> = {
    'prius': ['hybrid', 'sedan'],
    'aqua': ['hybrid', 'hatchback'],
    'fit': ['hatchback'],
    'vezel': ['suv'],
    'freed': ['minivan'],
    'stepwagon': ['minivan'],
    'civic': ['sedan'],
    'note': ['hatchback'],
    'serena': ['minivan'],
    'x-trail': ['suv'],
    'leaf': ['hatchback'],
    'jimny': ['4wd', 'kei', 'suv'],
    'spacia': ['kei', 'wagon'],
    'hustler': ['kei', 'suv'],
    'wagonr': ['kei', 'wagon'],
    'alto': ['kei', 'hatchback'],
    'cx-5': ['suv'],
    'cx-8': ['suv'],
    'mazda3': ['hatchback'],
    'cx-30': ['suv'],
    'tanto': ['kei', 'minivan'],
    'move': ['kei', 'hatchback'],
    'forester': ['suv'],
    'impreza': ['hatchback'],
    'levorg': ['wagon'],
  };
  return map[modelSeriesSlug] || [];
}

/**
 * 生データにslugを付与する関数
 */
function addSlugsToCarData(rawData: Omit<Car, 'makerSlug' | 'modelSlug' | 'prefSlug' | 'citySlug'>[]): Car[] {
  return rawData.map(car => ({
    ...car,
    makerSlug: MAKER_TO_SLUG[car.maker],
    modelSlug: modelToSlug(car.model),
    prefSlug: PREF_TO_SLUG[car.pref],
    citySlug: CITY_TO_SLUG[car.city],
    featureSlugs: inferFeatureSlugs(modelToSlug(car.model)),
  }));
}

// カーセンサーAPI代替のダミーデータ
// 実際のAPIが来たら、このファイルは不要になります
const rawCarData = [
  // トヨタ車
  {
    id: "c1",
    maker: "トヨタ",
    model: "プリウス S",
    year: 2020,
    mileage: 32000,
    hasRepairHistory: false,
    hasInspection: true,
    shaken: "車検整備付",
    warranty: "付き / 3ヵ月 / 3,000km",
    region: "関東",
    pref: "東京都",
    city: "港区",
    priceYen: 1780000,
    prevPriceYen: 1830000,
    updatedAt: now - 12 * 60 * 1000,
    postedAt: now - 8 * DAY,
    priceChangedAt: now - 3 * 60 * 60 * 1000,
    shop: "カーセレクト東京ベイ"
  },
  {
    id: "c2",
    maker: "トヨタ",
    model: "アクア G",
    year: 2021,
    mileage: 24000,
    hasRepairHistory: false,
    hasInspection: true,
    shaken: "2025年8月",
    warranty: "付き / 6ヵ月 / 6,000km",
    region: "関東",
    pref: "千葉県",
    city: "千葉市",
    priceYen: 1290000,
    prevPriceYen: 1290000,
    updatedAt: now - 5 * DAY,
    postedAt: now - 12 * DAY,
    priceChangedAt: null,
    shop: "千葉カーセンター"
  },
  {
    id: "c3",
    maker: "トヨタ",
    model: "ハリアー ハイブリッド",
    year: 2019,
    mileage: 45000,
    hasRepairHistory: false,
    hasInspection: true,
    shaken: "車検整備付",
    warranty: "付き / 12ヵ月 / 12,000km",
    region: "関東",
    pref: "神奈川県",
    city: "横浜市",
    priceYen: 3250000,
    prevPriceYen: 3350000,
    updatedAt: now - 2 * 60 * 60 * 1000,
    postedAt: now - 5 * DAY,
    priceChangedAt: now - 1 * DAY,
    shop: "横浜プレミアムカーズ"
  },
  {
    id: "c4",
    maker: "トヨタ",
    model: "アルファード S",
    year: 2020,
    mileage: 38000,
    hasRepairHistory: false,
    hasInspection: true,
    shaken: "2026年2月",
    warranty: "付き / 24ヵ月 / 無制限",
    region: "関西",
    pref: "大阪府",
    city: "大阪市",
    priceYen: 4280000,
    prevPriceYen: 4280000,
    updatedAt: now - 1 * DAY,
    postedAt: now - 7 * DAY,
    priceChangedAt: null,
    shop: "大阪高級車専門店"
  },
  {
    id: "c21",
    maker: "トヨタ",
    model: "ヤリス ハイブリッド",
    year: 2022,
    mileage: 15000,
    hasRepairHistory: false,
    hasInspection: true,
    shaken: "2027年1月",
    warranty: "付き / 6ヵ月 / 6,000km",
    region: "関東",
    pref: "東京都",
    city: "渋谷区",
    priceYen: 1650000,
    prevPriceYen: 1700000,
    updatedAt: now - 3 * 60 * 60 * 1000,
    postedAt: now - 4 * DAY,
    priceChangedAt: now - 18 * 60 * 60 * 1000,
    shop: "カーセレクト東京ベイ"
  },
  {
    id: "c22",
    maker: "トヨタ",
    model: "RAV4 アドベンチャー",
    year: 2021,
    mileage: 28000,
    hasRepairHistory: false,
    hasInspection: true,
    shaken: "車検整備付",
    warranty: "付き / 12ヵ月 / 12,000km",
    region: "中部",
    pref: "愛知県",
    city: "名古屋市",
    priceYen: 3580000,
    prevPriceYen: 3680000,
    updatedAt: now - 8 * 60 * 60 * 1000,
    postedAt: now - 6 * DAY,
    priceChangedAt: now - 2 * DAY,
    shop: "名古屋オートギャラリー"
  },
  {
    id: "c23",
    maker: "トヨタ",
    model: "カローラツーリング ハイブリッド",
    year: 2020,
    mileage: 35000,
    hasRepairHistory: false,
    hasInspection: true,
    shaken: "2025年10月",
    warranty: "付き / 3ヵ月 / 3,000km",
    region: "九州",
    pref: "福岡県",
    city: "福岡市",
    priceYen: 1980000,
    prevPriceYen: 1980000,
    updatedAt: now - 5 * 60 * 60 * 1000,
    postedAt: now - 10 * DAY,
    priceChangedAt: null,
    shop: "福岡カーライフステーション"
  },

  // ホンダ車
  {
    id: "c5",
    maker: "ホンダ",
    model: "N-BOX カスタム",
    year: 2021,
    mileage: 21000,
    hasRepairHistory: false,
    hasInspection: true,
    shaken: "2026年3月",
    warranty: "付き / 6ヵ月 / 6,000km",
    region: "関西",
    pref: "大阪府",
    city: "大阪市",
    priceYen: 1490000,
    prevPriceYen: 1490000,
    updatedAt: now - 40 * 60 * 1000,
    postedAt: now - 2 * DAY,
    priceChangedAt: null,
    shop: "大阪軽自動車センター"
  },
  {
    id: "c6",
    maker: "ホンダ",
    model: "フィット ハイブリッド",
    year: 2020,
    mileage: 42000,
    hasRepairHistory: false,
    hasInspection: true,
    shaken: "車検整備付",
    warranty: "付き / 3ヵ月 / 3,000km",
    region: "中部",
    pref: "愛知県",
    city: "名古屋市",
    priceYen: 1350000,
    prevPriceYen: 1420000,
    updatedAt: now - 3 * 60 * 60 * 1000,
    postedAt: now - 10 * DAY,
    priceChangedAt: now - 2 * DAY,
    shop: "名古屋オートギャラリー"
  },
  {
    id: "c7",
    maker: "ホンダ",
    model: "ヴェゼル e:HEV",
    year: 2022,
    mileage: 18000,
    hasRepairHistory: false,
    hasInspection: true,
    shaken: "2027年4月",
    warranty: "付き / 12ヵ月 / 12,000km",
    region: "関東",
    pref: "埼玉県",
    city: "さいたま市",
    priceYen: 2680000,
    prevPriceYen: 2780000,
    updatedAt: now - 6 * 60 * 60 * 1000,
    postedAt: now - 4 * DAY,
    priceChangedAt: now - 3 * DAY,
    shop: "埼玉カーステーション大宮"
  },
  {
    id: "c24",
    maker: "ホンダ",
    model: "フリード ハイブリッド",
    year: 2020,
    mileage: 37000,
    hasRepairHistory: false,
    hasInspection: true,
    shaken: "2025年11月",
    warranty: "付き / 6ヵ月 / 6,000km",
    region: "関東",
    pref: "千葉県",
    city: "船橋市",
    priceYen: 2180000,
    prevPriceYen: 2250000,
    updatedAt: now - 4 * 60 * 60 * 1000,
    postedAt: now - 7 * DAY,
    priceChangedAt: now - 1 * DAY,
    shop: "千葉カーセンター"
  },
  {
    id: "c25",
    maker: "ホンダ",
    model: "ステップワゴン e:HEV",
    year: 2023,
    mileage: 8000,
    hasRepairHistory: false,
    hasInspection: true,
    shaken: "2028年2月",
    warranty: "付き / 24ヵ月 / 無制限",
    region: "関西",
    pref: "兵庫県",
    city: "神戸市",
    priceYen: 3380000,
    prevPriceYen: 3380000,
    updatedAt: now - 2 * 60 * 60 * 1000,
    postedAt: now - 3 * DAY,
    priceChangedAt: null,
    shop: "神戸ファミリーカー"
  },
  {
    id: "c26",
    maker: "ホンダ",
    model: "シビック Type R",
    year: 2019,
    mileage: 51000,
    hasRepairHistory: true,
    hasInspection: true,
    shaken: "車検整備付",
    warranty: "付き / 3ヵ月 / 3,000km",
    region: "関東",
    pref: "神奈川県",
    city: "横浜市",
    priceYen: 4580000,
    prevPriceYen: 4680000,
    updatedAt: now - 9 * 60 * 60 * 1000,
    postedAt: now - 8 * DAY,
    priceChangedAt: now - 4 * DAY,
    shop: "横浜プレミアムカーズ"
  },

  // 日産車
  {
    id: "c8",
    maker: "日産",
    model: "ノート e-POWER",
    year: 2019,
    mileage: 55000,
    hasRepairHistory: false,
    hasInspection: true,
    shaken: "車検整備付",
    warranty: "付き / 3ヵ月 / 3,000km",
    region: "中部",
    pref: "愛知県",
    city: "名古屋市",
    priceYen: 1120000,
    prevPriceYen: 1180000,
    updatedAt: now - 2 * 60 * 60 * 1000,
    postedAt: now - 15 * DAY,
    priceChangedAt: now - 20 * 60 * 60 * 1000,
    shop: "名古屋オートギャラリー"
  },
  {
    id: "c9",
    maker: "日産",
    model: "セレナ e-POWER",
    year: 2020,
    mileage: 40000,
    hasRepairHistory: false,
    hasInspection: true,
    shaken: "2025年9月",
    warranty: "付き / 12ヵ月 / 12,000km",
    region: "関東",
    pref: "東京都",
    city: "世田谷区",
    priceYen: 2890000,
    prevPriceYen: 2990000,
    updatedAt: now - 1 * 60 * 60 * 1000,
    postedAt: now - 6 * DAY,
    priceChangedAt: now - 12 * 60 * 60 * 1000,
    shop: "東京ファミリーカー専門館"
  },
  {
    id: "c10",
    maker: "日産",
    model: "エクストレイル",
    year: 2021,
    mileage: 31000,
    hasRepairHistory: false,
    hasInspection: true,
    shaken: "2026年7月",
    warranty: "付き / 6ヵ月 / 6,000km",
    region: "九州",
    pref: "福岡県",
    city: "福岡市",
    priceYen: 2450000,
    prevPriceYen: 2450000,
    updatedAt: now - 8 * 60 * 60 * 1000,
    postedAt: now - 9 * DAY,
    priceChangedAt: null,
    shop: "福岡SUV専門館"
  },
  {
    id: "c27",
    maker: "日産",
    model: "リーフ",
    year: 2021,
    mileage: 22000,
    hasRepairHistory: false,
    hasInspection: true,
    shaken: "2026年5月",
    warranty: "付き / 12ヵ月 / 12,000km",
    region: "関東",
    pref: "東京都",
    city: "港区",
    priceYen: 2380000,
    prevPriceYen: 2480000,
    updatedAt: now - 5 * 60 * 60 * 1000,
    postedAt: now - 5 * DAY,
    priceChangedAt: now - 2 * DAY,
    shop: "カーセレクト東京ベイ"
  },
  {
    id: "c28",
    maker: "日産",
    model: "キックス e-POWER",
    year: 2022,
    mileage: 16000,
    hasRepairHistory: false,
    hasInspection: true,
    shaken: "2027年3月",
    warranty: "付き / 6ヵ月 / 6,000km",
    region: "関西",
    pref: "京都府",
    city: "京都市",
    priceYen: 2580000,
    prevPriceYen: 2580000,
    updatedAt: now - 7 * 60 * 60 * 1000,
    postedAt: now - 11 * DAY,
    priceChangedAt: null,
    shop: "京都プレミアムオート"
  },

  // スズキ車
  {
    id: "c11",
    maker: "スズキ",
    model: "ジムニー",
    year: 2022,
    mileage: 12000,
    hasRepairHistory: false,
    hasInspection: true,
    shaken: "2027年2月",
    warranty: "付き / 12ヵ月 / 12,000km",
    region: "九州",
    pref: "福岡県",
    city: "福岡市",
    priceYen: 2150000,
    prevPriceYen: 2100000,
    updatedAt: now - 25 * 60 * 1000,
    postedAt: now - 6 * DAY,
    priceChangedAt: now - 90 * 60 * 1000,
    shop: "福岡カーライフステーション"
  },
  {
    id: "c12",
    maker: "スズキ",
    model: "スペーシア カスタム",
    year: 2021,
    mileage: 26000,
    hasRepairHistory: false,
    hasInspection: true,
    shaken: "2026年4月",
    warranty: "付き / 6ヵ月 / 6,000km",
    region: "関西",
    pref: "兵庫県",
    city: "神戸市",
    priceYen: 1380000,
    prevPriceYen: 1380000,
    updatedAt: now - 4 * DAY,
    postedAt: now - 11 * DAY,
    priceChangedAt: null,
    shop: "神戸ファミリーカー"
  },
  {
    id: "c13",
    maker: "スズキ",
    model: "ハスラー ハイブリッド",
    year: 2020,
    mileage: 38000,
    hasRepairHistory: false,
    hasInspection: true,
    shaken: "車検整備付",
    warranty: "付き / 3ヵ月 / 3,000km",
    region: "中部",
    pref: "静岡県",
    city: "浜松市",
    priceYen: 1180000,
    prevPriceYen: 1230000,
    updatedAt: now - 10 * 60 * 60 * 1000,
    postedAt: now - 14 * DAY,
    priceChangedAt: now - 5 * DAY,
    shop: "浜松カーライフ"
  },
  {
    id: "c29",
    maker: "スズキ",
    model: "ワゴンR スティングレー",
    year: 2021,
    mileage: 29000,
    hasRepairHistory: false,
    hasInspection: true,
    shaken: "2026年6月",
    warranty: "付き / 3ヵ月 / 3,000km",
    region: "関西",
    pref: "大阪府",
    city: "堺市",
    priceYen: 1180000,
    prevPriceYen: 1250000,
    updatedAt: now - 6 * 60 * 60 * 1000,
    postedAt: now - 9 * DAY,
    priceChangedAt: now - 3 * DAY,
    shop: "大阪軽自動車センター"
  },
  {
    id: "c30",
    maker: "スズキ",
    model: "アルト ラパン",
    year: 2022,
    mileage: 9000,
    hasRepairHistory: false,
    hasInspection: true,
    shaken: "2027年5月",
    warranty: "付き / 6ヵ月 / 6,000km",
    region: "九州",
    pref: "熊本県",
    city: "熊本市",
    priceYen: 1250000,
    prevPriceYen: 1250000,
    updatedAt: now - 3 * 60 * 60 * 1000,
    postedAt: now - 5 * DAY,
    priceChangedAt: null,
    shop: "熊本カーステーション"
  },

  // マツダ車
  {
    id: "c14",
    maker: "マツダ",
    model: "CX-5",
    year: 2018,
    mileage: 68000,
    hasRepairHistory: false,
    hasInspection: true,
    shaken: "車検整備付",
    warranty: "付き / 3ヵ月 / 3,000km",
    region: "関東",
    pref: "神奈川県",
    city: "横浜市",
    priceYen: 1680000,
    prevPriceYen: 1680000,
    updatedAt: now - 3 * DAY,
    postedAt: now - 28 * DAY,
    priceChangedAt: null,
    shop: "横浜プレミアムカーズ"
  },
  {
    id: "c15",
    maker: "マツダ",
    model: "CX-8",
    year: 2020,
    mileage: 41000,
    hasRepairHistory: false,
    hasInspection: true,
    shaken: "2025年12月",
    warranty: "付き / 12ヵ月 / 12,000km",
    region: "関西",
    pref: "京都府",
    city: "京都市",
    priceYen: 2980000,
    prevPriceYen: 3080000,
    updatedAt: now - 30 * 60 * 1000,
    postedAt: now - 3 * DAY,
    priceChangedAt: now - 6 * 60 * 60 * 1000,
    shop: "京都プレミアムオート"
  },
  {
    id: "c16",
    maker: "マツダ",
    model: "MAZDA3 ファストバック",
    year: 2021,
    mileage: 25000,
    hasRepairHistory: false,
    hasInspection: true,
    shaken: "2026年9月",
    warranty: "付き / 6ヵ月 / 6,000km",
    region: "中部",
    pref: "愛知県",
    city: "豊田市",
    priceYen: 2120000,
    prevPriceYen: 2120000,
    updatedAt: now - 2 * DAY,
    postedAt: now - 8 * DAY,
    priceChangedAt: null,
    shop: "豊田カーセンター"
  },
  {
    id: "c31",
    maker: "マツダ",
    model: "CX-30",
    year: 2022,
    mileage: 14000,
    hasRepairHistory: false,
    hasInspection: true,
    shaken: "2027年6月",
    warranty: "付き / 12ヵ月 / 12,000km",
    region: "関東",
    pref: "埼玉県",
    city: "さいたま市",
    priceYen: 2680000,
    prevPriceYen: 2750000,
    updatedAt: now - 4 * 60 * 60 * 1000,
    postedAt: now - 6 * DAY,
    priceChangedAt: now - 1 * DAY,
    shop: "埼玉カーステーション大宮"
  },
  {
    id: "c32",
    maker: "マツダ",
    model: "ロードスター S",
    year: 2019,
    mileage: 48000,
    hasRepairHistory: false,
    hasInspection: true,
    shaken: "車検整備付",
    warranty: "付き / 3ヵ月 / 3,000km",
    region: "関西",
    pref: "大阪府",
    city: "大阪市",
    priceYen: 2380000,
    prevPriceYen: 2380000,
    updatedAt: now - 8 * 60 * 60 * 1000,
    postedAt: now - 12 * DAY,
    priceChangedAt: null,
    shop: "大阪スポーツカー専門"
  },

  // ダイハツ車
  {
    id: "c17",
    maker: "ダイハツ",
    model: "タント カスタム",
    year: 2021,
    mileage: 23000,
    hasRepairHistory: false,
    hasInspection: true,
    shaken: "2026年8月",
    warranty: "付き / 6ヵ月 / 6,000km",
    region: "関東",
    pref: "千葉県",
    city: "船橋市",
    priceYen: 1420000,
    prevPriceYen: 1470000,
    updatedAt: now - 5 * 60 * 60 * 1000,
    postedAt: now - 7 * DAY,
    priceChangedAt: now - 1 * DAY,
    shop: "千葉カーセンター"
  },
  {
    id: "c18",
    maker: "ダイハツ",
    model: "ムーヴ キャンバス",
    year: 2020,
    mileage: 39000,
    hasRepairHistory: false,
    hasInspection: true,
    shaken: "車検整備付",
    warranty: "付き / 3ヵ月 / 3,000km",
    region: "九州",
    pref: "熊本県",
    city: "熊本市",
    priceYen: 1150000,
    prevPriceYen: 1150000,
    updatedAt: now - 6 * DAY,
    postedAt: now - 13 * DAY,
    priceChangedAt: null,
    shop: "熊本カーステーション"
  },
  {
    id: "c33",
    maker: "ダイハツ",
    model: "ムーヴ カスタム",
    year: 2021,
    mileage: 27000,
    hasRepairHistory: false,
    hasInspection: true,
    shaken: "2026年10月",
    warranty: "付き / 6ヵ月 / 6,000km",
    region: "関西",
    pref: "大阪府",
    city: "大阪市",
    priceYen: 1280000,
    prevPriceYen: 1350000,
    updatedAt: now - 7 * 60 * 60 * 1000,
    postedAt: now - 10 * DAY,
    priceChangedAt: now - 4 * DAY,
    shop: "大阪軽自動車センター"
  },
  {
    id: "c34",
    maker: "ダイハツ",
    model: "ロッキー プレミアム",
    year: 2022,
    mileage: 13000,
    hasRepairHistory: false,
    hasInspection: true,
    shaken: "2027年7月",
    warranty: "付き / 12ヵ月 / 12,000km",
    region: "中部",
    pref: "静岡県",
    city: "浜松市",
    priceYen: 1880000,
    prevPriceYen: 1880000,
    updatedAt: now - 5 * 60 * 60 * 1000,
    postedAt: now - 7 * DAY,
    priceChangedAt: null,
    shop: "浜松カーライフ"
  },

  // スバル車
  {
    id: "c19",
    maker: "スバル",
    model: "フォレスター Advance",
    year: 2020,
    mileage: 43000,
    hasRepairHistory: false,
    hasInspection: true,
    shaken: "2025年7月",
    warranty: "付き / 12ヵ月 / 12,000km",
    region: "東北",
    pref: "宮城県",
    city: "仙台市",
    priceYen: 2650000,
    prevPriceYen: 2750000,
    updatedAt: now - 4 * 60 * 60 * 1000,
    postedAt: now - 5 * DAY,
    priceChangedAt: now - 2 * DAY,
    shop: "仙台4WD専門館"
  },
  {
    id: "c20",
    maker: "スバル",
    model: "インプレッサ スポーツ",
    year: 2019,
    mileage: 58000,
    hasRepairHistory: false,
    hasInspection: true,
    shaken: "車検整備付",
    warranty: "付き / 3ヵ月 / 3,000km",
    region: "関東",
    pref: "東京都",
    city: "新宿区",
    priceYen: 1580000,
    prevPriceYen: 1580000,
    updatedAt: now - 7 * DAY,
    postedAt: now - 20 * DAY,
    priceChangedAt: null,
    shop: "東京ファミリーカー専門館"
  },
  {
    id: "c35",
    maker: "スバル",
    model: "XV アドバンス",
    year: 2021,
    mileage: 33000,
    hasRepairHistory: false,
    hasInspection: true,
    shaken: "2026年11月",
    warranty: "付き / 12ヵ月 / 12,000km",
    region: "東北",
    pref: "宮城県",
    city: "仙台市",
    priceYen: 2480000,
    prevPriceYen: 2580000,
    updatedAt: now - 6 * 60 * 60 * 1000,
    postedAt: now - 8 * DAY,
    priceChangedAt: now - 3 * DAY,
    shop: "仙台4WD専門館"
  },
  {
    id: "c36",
    maker: "スバル",
    model: "レヴォーグ STI Sport",
    year: 2020,
    mileage: 46000,
    hasRepairHistory: false,
    hasInspection: true,
    shaken: "車検整備付",
    warranty: "付き / 6ヵ月 / 6,000km",
    region: "関東",
    pref: "神奈川県",
    city: "横浜市",
    priceYen: 3180000,
    prevPriceYen: 3180000,
    updatedAt: now - 9 * 60 * 60 * 1000,
    postedAt: now - 14 * DAY,
    priceChangedAt: null,
    shop: "横浜プレミアムカーズ"
  },

  // 三菱車
  {
    id: "c37",
    maker: "三菱",
    model: "デリカ D:5",
    year: 2020,
    mileage: 49000,
    hasRepairHistory: false,
    hasInspection: true,
    shaken: "2025年6月",
    warranty: "付き / 6ヵ月 / 6,000km",
    region: "東北",
    pref: "宮城県",
    city: "仙台市",
    priceYen: 2980000,
    prevPriceYen: 3080000,
    updatedAt: now - 10 * 60 * 60 * 1000,
    postedAt: now - 11 * DAY,
    priceChangedAt: now - 5 * DAY,
    shop: "仙台4WD専門館"
  },
  {
    id: "c38",
    maker: "三菱",
    model: "eKワゴン",
    year: 2021,
    mileage: 19000,
    hasRepairHistory: false,
    hasInspection: true,
    shaken: "2026年12月",
    warranty: "付き / 6ヵ月 / 6,000km",
    region: "九州",
    pref: "福岡県",
    city: "福岡市",
    priceYen: 980000,
    prevPriceYen: 980000,
    updatedAt: now - 5 * 60 * 60 * 1000,
    postedAt: now - 9 * DAY,
    priceChangedAt: null,
    shop: "福岡カーライフステーション"
  },
  {
    id: "c39",
    maker: "三菱",
    model: "アウトランダーPHEV",
    year: 2022,
    mileage: 17000,
    hasRepairHistory: false,
    hasInspection: true,
    shaken: "2027年8月",
    warranty: "付き / 24ヵ月 / 無制限",
    region: "関東",
    pref: "東京都",
    city: "港区",
    priceYen: 4280000,
    prevPriceYen: 4380000,
    updatedAt: now - 3 * 60 * 60 * 1000,
    postedAt: now - 4 * DAY,
    priceChangedAt: now - 1 * DAY,
    shop: "カーセレクト東京ベイ"
  },

  // レクサス車
  {
    id: "c40",
    maker: "レクサス",
    model: "NX300h",
    year: 2019,
    mileage: 52000,
    hasRepairHistory: false,
    hasInspection: true,
    shaken: "車検整備付",
    warranty: "付き / 24ヵ月 / 無制限",
    region: "関東",
    pref: "東京都",
    city: "港区",
    priceYen: 4580000,
    prevPriceYen: 4580000,
    updatedAt: now - 2 * DAY,
    postedAt: now - 15 * DAY,
    priceChangedAt: null,
    shop: "東京プレミアムカーセレクト"
  },
  {
    id: "c41",
    maker: "レクサス",
    model: "RX450h",
    year: 2020,
    mileage: 36000,
    hasRepairHistory: false,
    hasInspection: true,
    shaken: "2025年5月",
    warranty: "付き / 24ヵ月 / 無制限",
    region: "関西",
    pref: "大阪府",
    city: "大阪市",
    priceYen: 5680000,
    prevPriceYen: 5880000,
    updatedAt: now - 4 * 60 * 60 * 1000,
    postedAt: now - 6 * DAY,
    priceChangedAt: now - 2 * DAY,
    shop: "大阪高級車専門店"
  },
  {
    id: "c42",
    maker: "レクサス",
    model: "CT200h",
    year: 2018,
    mileage: 62000,
    hasRepairHistory: false,
    hasInspection: true,
    shaken: "車検整備付",
    warranty: "付き / 12ヵ月 / 12,000km",
    region: "関東",
    pref: "神奈川県",
    city: "横浜市",
    priceYen: 2380000,
    prevPriceYen: 2480000,
    updatedAt: now - 8 * 60 * 60 * 1000,
    postedAt: now - 12 * DAY,
    priceChangedAt: now - 6 * DAY,
    shop: "横浜プレミアムカーズ"
  },

  // 輸入車
  {
    id: "c43",
    maker: "メルセデス・ベンツ",
    model: "Cクラス C200",
    year: 2019,
    mileage: 44000,
    hasRepairHistory: false,
    hasInspection: true,
    shaken: "車検整備付",
    warranty: "付き / 12ヵ月 / 12,000km",
    region: "関東",
    pref: "東京都",
    city: "港区",
    priceYen: 3280000,
    prevPriceYen: 3380000,
    updatedAt: now - 5 * 60 * 60 * 1000,
    postedAt: now - 10 * DAY,
    priceChangedAt: now - 3 * DAY,
    shop: "東京プレミアムカーセレクト"
  },
  {
    id: "c44",
    maker: "BMW",
    model: "3シリーズ 320i",
    year: 2020,
    mileage: 38000,
    hasRepairHistory: false,
    hasInspection: true,
    shaken: "2025年4月",
    warranty: "付き / 24ヵ月 / 無制限",
    region: "関西",
    pref: "大阪府",
    city: "大阪市",
    priceYen: 3580000,
    prevPriceYen: 3580000,
    updatedAt: now - 6 * 60 * 60 * 1000,
    postedAt: now - 13 * DAY,
    priceChangedAt: null,
    shop: "大阪高級車専門店"
  },
  {
    id: "c45",
    maker: "フォルクスワーゲン",
    model: "ゴルフ TSI",
    year: 2021,
    mileage: 26000,
    hasRepairHistory: false,
    hasInspection: true,
    shaken: "2026年1月",
    warranty: "付き / 12ヵ月 / 12,000km",
    region: "関東",
    pref: "神奈川県",
    city: "横浜市",
    priceYen: 2180000,
    prevPriceYen: 2280000,
    updatedAt: now - 7 * 60 * 60 * 1000,
    postedAt: now - 9 * DAY,
    priceChangedAt: now - 4 * DAY,
    shop: "横浜プレミアムカーズ"
  },
  {
    id: "c46",
    maker: "アウディ",
    model: "A4 35TFSI",
    year: 2020,
    mileage: 41000,
    hasRepairHistory: false,
    hasInspection: true,
    shaken: "車検整備付",
    warranty: "付き / 12ヵ月 / 12,000km",
    region: "中部",
    pref: "愛知県",
    city: "名古屋市",
    priceYen: 3480000,
    prevPriceYen: 3480000,
    updatedAt: now - 9 * 60 * 60 * 1000,
    postedAt: now - 16 * DAY,
    priceChangedAt: null,
    shop: "名古屋インポートカー"
  },
  {
    id: "c47",
    maker: "ボルボ",
    model: "XC60 T5",
    year: 2019,
    mileage: 47000,
    hasRepairHistory: false,
    hasInspection: true,
    shaken: "車検整備付",
    warranty: "付き / 12ヵ月 / 12,000km",
    region: "関東",
    pref: "東京都",
    city: "世田谷区",
    priceYen: 3880000,
    prevPriceYen: 3980000,
    updatedAt: now - 11 * 60 * 60 * 1000,
    postedAt: now - 14 * DAY,
    priceChangedAt: now - 7 * DAY,
    shop: "東京ファミリーカー専門館"
  },
  {
    id: "c48",
    maker: "MINI",
    model: "MINI クーパー",
    year: 2021,
    mileage: 20000,
    hasRepairHistory: false,
    hasInspection: true,
    shaken: "2026年2月",
    warranty: "付き / 12ヵ月 / 12,000km",
    region: "関西",
    pref: "京都府",
    city: "京都市",
    priceYen: 2580000,
    prevPriceYen: 2680000,
    updatedAt: now - 4 * 60 * 60 * 1000,
    postedAt: now - 8 * DAY,
    priceChangedAt: now - 2 * DAY,
    shop: "京都プレミアムオート"
  },
  {
    id: "c49",
    maker: "ジープ",
    model: "ラングラー アンリミテッド",
    year: 2020,
    mileage: 35000,
    hasRepairHistory: true,
    hasInspection: true,
    shaken: "車検整備付",
    warranty: "付き / 6ヵ月 / 6,000km",
    region: "九州",
    pref: "福岡県",
    city: "福岡市",
    priceYen: 4680000,
    prevPriceYen: 4680000,
    updatedAt: now - 12 * 60 * 60 * 1000,
    postedAt: now - 17 * DAY,
    priceChangedAt: null,
    shop: "福岡SUV専門館"
  },
  {
    id: "c50",
    maker: "プジョー",
    model: "308 アリュール",
    year: 2021,
    mileage: 30000,
    hasRepairHistory: false,
    hasInspection: true,
    shaken: "2026年5月",
    warranty: "付き / 12ヵ月 / 12,000km",
    region: "関東",
    pref: "東京都",
    city: "港区",
    priceYen: 2280000,
    prevPriceYen: 2380000,
    updatedAt: now - 13 * 60 * 60 * 1000,
    postedAt: now - 11 * DAY,
    priceChangedAt: now - 5 * DAY,
    shop: "東京プレミアムカーセレクト"
  },

  // 古いデータ（30日以上前）- フィルタリングでテスト用
  {
    id: "c_old_1",
    maker: "トヨタ",
    model: "アクア",
    year: 2017,
    mileage: 82000,
    hasRepairHistory: true,
    hasInspection: false,
    shaken: "なし",
    warranty: "なし",
    region: "関東",
    pref: "千葉県",
    city: "千葉市",
    priceYen: 790000,
    prevPriceYen: 820000,
    updatedAt: now - 31 * DAY,
    postedAt: now - 40 * DAY,
    priceChangedAt: now - 35 * DAY,
    shop: "千葉中古車マート"
  },
  {
    id: "c_old_2",
    maker: "ホンダ",
    model: "フリード",
    year: 2016,
    mileage: 95000,
    hasRepairHistory: false,
    hasInspection: false,
    shaken: "なし",
    warranty: "なし",
    region: "関西",
    pref: "大阪府",
    city: "堺市",
    priceYen: 980000,
    prevPriceYen: 980000,
    updatedAt: now - 45 * DAY,
    postedAt: now - 60 * DAY,
    priceChangedAt: null,
    shop: "堺カーセンター"
  }
];

// slug付きでエクスポート
export const mockCarDatabase: Car[] = addSlugsToCarData(rawCarData);
