// src\lib\mockCars.ts
import type { Car } from '@/types';

const now = Date.now();
const DAY = 24 * 60 * 60 * 1000;

// カーセンサーAPI代替のダミーデータ
// 実際のAPIが来たら、このファイルは不要になります
export const mockCarDatabase: Car[] = [
  // トヨタ車
  {
    id: "c1",
    maker: "トヨタ",
    model: "プリウス S",
    year: 2020,
    region: "関東",
    pref: "東京都",
    city: "港区",
    priceYen: 1780000,
    prevPriceYen: 1830000,
    updatedAt: now - 12 * 60 * 1000,
    postedAt: now - 8 * DAY,
    priceChangedAt: now - 3 * 60 * 60 * 1000,
    shop: "○○モータース"
  },
  {
    id: "c2",
    maker: "トヨタ",
    model: "アクア G",
    year: 2021,
    region: "関東",
    pref: "千葉県",
    city: "千葉市",
    priceYen: 1290000,
    prevPriceYen: 1290000,
    updatedAt: now - 5 * DAY,
    postedAt: now - 12 * DAY,
    priceChangedAt: null,
    shop: "千葉カーセンター"
  },
  {
    id: "c3",
    maker: "トヨタ",
    model: "ハリアー ハイブリッド",
    year: 2019,
    region: "関東",
    pref: "神奈川県",
    city: "横浜市",
    priceYen: 3250000,
    prevPriceYen: 3350000,
    updatedAt: now - 2 * 60 * 60 * 1000,
    postedAt: now - 5 * DAY,
    priceChangedAt: now - 1 * DAY,
    shop: "横浜カーセレクト"
  },
  {
    id: "c4",
    maker: "トヨタ",
    model: "アルファード S",
    year: 2020,
    region: "関西",
    pref: "大阪府",
    city: "大阪市",
    priceYen: 4280000,
    prevPriceYen: 4280000,
    updatedAt: now - 1 * DAY,
    postedAt: now - 7 * DAY,
    priceChangedAt: null,
    shop: "大阪プレミアムカー"
  },

  // ホンダ車
  {
    id: "c5",
    maker: "ホンダ",
    model: "N-BOX カスタム",
    year: 2021,
    region: "関西",
    pref: "大阪府",
    city: "大阪市",
    priceYen: 1490000,
    prevPriceYen: 1490000,
    updatedAt: now - 40 * 60 * 1000,
    postedAt: now - 2 * DAY,
    priceChangedAt: null,
    shop: "カーショップA"
  },
  {
    id: "c6",
    maker: "ホンダ",
    model: "フィット ハイブリッド",
    year: 2020,
    region: "中部",
    pref: "愛知県",
    city: "名古屋市",
    priceYen: 1350000,
    prevPriceYen: 1420000,
    updatedAt: now - 3 * 60 * 60 * 1000,
    postedAt: now - 10 * DAY,
    priceChangedAt: now - 2 * DAY,
    shop: "名古屋オートモール"
  },
  {
    id: "c7",
    maker: "ホンダ",
    model: "ヴェゼル e:HEV",
    year: 2022,
    region: "関東",
    pref: "埼玉県",
    city: "さいたま市",
    priceYen: 2680000,
    prevPriceYen: 2780000,
    updatedAt: now - 6 * 60 * 60 * 1000,
    postedAt: now - 4 * DAY,
    priceChangedAt: now - 3 * DAY,
    shop: "埼玉カーステーション"
  },

  // 日産車
  {
    id: "c8",
    maker: "日産",
    model: "ノート e-POWER",
    year: 2019,
    region: "中部",
    pref: "愛知県",
    city: "名古屋市",
    priceYen: 1120000,
    prevPriceYen: 1180000,
    updatedAt: now - 2 * 60 * 60 * 1000,
    postedAt: now - 15 * DAY,
    priceChangedAt: now - 20 * 60 * 60 * 1000,
    shop: "クルマ館"
  },
  {
    id: "c9",
    maker: "日産",
    model: "セレナ e-POWER",
    year: 2020,
    region: "関東",
    pref: "東京都",
    city: "世田谷区",
    priceYen: 2890000,
    prevPriceYen: 2990000,
    updatedAt: now - 1 * 60 * 60 * 1000,
    postedAt: now - 6 * DAY,
    priceChangedAt: now - 12 * 60 * 60 * 1000,
    shop: "東京ファミリーカー"
  },
  {
    id: "c10",
    maker: "日産",
    model: "エクストレイル",
    year: 2021,
    region: "九州",
    pref: "福岡県",
    city: "福岡市",
    priceYen: 2450000,
    prevPriceYen: 2450000,
    updatedAt: now - 8 * 60 * 60 * 1000,
    postedAt: now - 9 * DAY,
    priceChangedAt: null,
    shop: "福岡SUV専門店"
  },

  // スズキ車
  {
    id: "c11",
    maker: "スズキ",
    model: "ジムニー",
    year: 2022,
    region: "九州",
    pref: "福岡県",
    city: "福岡市",
    priceYen: 2150000,
    prevPriceYen: 2100000,
    updatedAt: now - 25 * 60 * 1000,
    postedAt: now - 6 * DAY,
    priceChangedAt: now - 90 * 60 * 1000,
    shop: "九州オート"
  },
  {
    id: "c12",
    maker: "スズキ",
    model: "スペーシア カスタム",
    year: 2021,
    region: "関西",
    pref: "兵庫県",
    city: "神戸市",
    priceYen: 1380000,
    prevPriceYen: 1380000,
    updatedAt: now - 4 * DAY,
    postedAt: now - 11 * DAY,
    priceChangedAt: null,
    shop: "神戸軽自動車専門"
  },
  {
    id: "c13",
    maker: "スズキ",
    model: "ハスラー ハイブリッド",
    year: 2020,
    region: "中部",
    pref: "静岡県",
    city: "浜松市",
    priceYen: 1180000,
    prevPriceYen: 1230000,
    updatedAt: now - 10 * 60 * 60 * 1000,
    postedAt: now - 14 * DAY,
    priceChangedAt: now - 5 * DAY,
    shop: "浜松カーライフ"
  },

  // マツダ車
  {
    id: "c14",
    maker: "マツダ",
    model: "CX-5",
    year: 2018,
    region: "関東",
    pref: "神奈川県",
    city: "横浜市",
    priceYen: 1680000,
    prevPriceYen: 1680000,
    updatedAt: now - 3 * DAY,
    postedAt: now - 28 * DAY,
    priceChangedAt: null,
    shop: "横浜カーセレクト"
  },
  {
    id: "c15",
    maker: "マツダ",
    model: "CX-8",
    year: 2020,
    region: "関西",
    pref: "京都府",
    city: "京都市",
    priceYen: 2980000,
    prevPriceYen: 3080000,
    updatedAt: now - 30 * 60 * 1000,
    postedAt: now - 3 * DAY,
    priceChangedAt: now - 6 * 60 * 60 * 1000,
    shop: "京都プレミアムオート"
  },
  {
    id: "c16",
    maker: "マツダ",
    model: "MAZDA3 ファストバック",
    year: 2021,
    region: "中部",
    pref: "愛知県",
    city: "豊田市",
    priceYen: 2120000,
    prevPriceYen: 2120000,
    updatedAt: now - 2 * DAY,
    postedAt: now - 8 * DAY,
    priceChangedAt: null,
    shop: "豊田カーセンター"
  },

  // ダイハツ車
  {
    id: "c17",
    maker: "ダイハツ",
    model: "タント カスタム",
    year: 2021,
    region: "関東",
    pref: "千葉県",
    city: "船橋市",
    priceYen: 1420000,
    prevPriceYen: 1470000,
    updatedAt: now - 5 * 60 * 60 * 1000,
    postedAt: now - 7 * DAY,
    priceChangedAt: now - 1 * DAY,
    shop: "船橋軽カー専門"
  },
  {
    id: "c18",
    maker: "ダイハツ",
    model: "ムーヴ キャンバス",
    year: 2020,
    region: "九州",
    pref: "熊本県",
    city: "熊本市",
    priceYen: 1150000,
    prevPriceYen: 1150000,
    updatedAt: now - 6 * DAY,
    postedAt: now - 13 * DAY,
    priceChangedAt: null,
    shop: "熊本カーライフ"
  },

  // スバル車
  {
    id: "c19",
    maker: "スバル",
    model: "フォレスター Advance",
    year: 2020,
    region: "東北",
    pref: "宮城県",
    city: "仙台市",
    priceYen: 2650000,
    prevPriceYen: 2750000,
    updatedAt: now - 4 * 60 * 60 * 1000,
    postedAt: now - 5 * DAY,
    priceChangedAt: now - 2 * DAY,
    shop: "仙台4WD専門"
  },
  {
    id: "c20",
    maker: "スバル",
    model: "インプレッサ スポーツ",
    year: 2019,
    region: "関東",
    pref: "東京都",
    city: "新宿区",
    priceYen: 1580000,
    prevPriceYen: 1580000,
    updatedAt: now - 7 * DAY,
    postedAt: now - 20 * DAY,
    priceChangedAt: null,
    shop: "新宿カーステーション"
  },

  // 古いデータ（30日以上前）
  {
    id: "c_old_1",
    maker: "トヨタ",
    model: "アクア",
    year: 2017,
    region: "関東",
    pref: "千葉県",
    city: "千葉市",
    priceYen: 790000,
    prevPriceYen: 820000,
    updatedAt: now - 31 * DAY,
    postedAt: now - 40 * DAY,
    priceChangedAt: now - 35 * DAY,
    shop: "古いデータ屋"
  },
  {
    id: "c_old_2",
    maker: "ホンダ",
    model: "フリード",
    year: 2016,
    region: "関西",
    pref: "大阪府",
    city: "堺市",
    priceYen: 980000,
    prevPriceYen: 980000,
    updatedAt: now - 45 * DAY,
    postedAt: now - 60 * DAY,
    priceChangedAt: null,
    shop: "旧車センター"
  }
];
